config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'splashs#index'
  resources :splashs, only: [:index, :show, :new, :create]
  resources :groups do
    resources :entities
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups
  validates :name, presence: true, uniqueness: true
  validates :amount,
            presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :entities
  # has_one_attached :icon
  validates :name, presence: true, uniqueness: { scope: :user_id, message: 'has already been taken for this user' }
  validates :icon, presence: true, format: { with: /.+\.png\z/, message: "must end with '.png'" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_many :entities, dependent: :destroy
  has_many :groups, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :password, :current_password)
    end
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_group

  def new
    @current_user = current_user
    @entity = Entity.new
    @groups = current_user.groups
  end

  def destroy
    @entity = Entity.find(params[:id]).destroy
    respond_to do |f|
      f.html { redirect_to group_path(@group), notice: 'The Transaction has been deleted successfully' }
    end
  end

  def create
    @current_user = current_user
    @entity = Entity.new(name: params[:entity][:name], amount: params[:entity][:amount])
    @entity.user = @current_user
    @groups_id = params[:entity][:category_id]
    @groups_id.each do |category_id|
      group = Group.find(category_id)
      @entity.groups << group
    end
    if @entity.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, category_id: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @current_user = current_user
    @group = Group.new
  end

  def create
    @current_user = current_user
    @group = Group.new(group_params)
    @group.user = @current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(request.params['id'])
    @current_user = current_user
    @entities = Entity.joins(:entities_groups).where(entities_groups: { group_id: @group.id },
                                                     user_id: @current_user.id).order(created_at: :desc)
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splashs_controller.rb
class SplashsController < ApplicationController
  def index
    # Empty action as the view is responsible for the  screen content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/entities/new.html.erb
<%= form_with model: @entity, url: group_entities_path(@group), method: :post, local: true, html: { class: "newFormEntities" } do |f| %>
  <div class="newEntityHeader">
    <div class ="backArrow">
      <%= link_to group_path(@group) do %>
        <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "backArrowImg" %>
      <% end %>
    </div>
    <h2>ADD EXPENSE</h2>
    <%= f.submit "ADD", class: "submitNewEntity" %>
  </div>
  <div class = "newEntityBody">
    <div class="fieldNameNewEntity">
      <%= f.text_field :name, autocomplete: "Entity name", placeholder: "Name", class: "loginField", require: true %>
    </div>
    <div class="fieldNameNewEntity">
      <%= f.text_field :amount, autocomplete: "Amount", placeholder: "Amount", class: "loginField", require: true %>
    </div>
    <div class="fieldNameNewEntity">
      <% if @groups.present? %>
        <% @groups.each do |group| %>
          <p>
            <%= f.check_box :category_id, { multiple: true }, group.id, nil %>
            <%= group.name %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<section class="containerCategories">
  <div class="categoriesHeader">
    <div class="hamburger">
      <%= image_tag "hamburger.png", alt: "Hamburger Icon", class: "hamburgerImg" %>
    </div>
    <h2>CATEGORIES</h2>
    <div class="search">
      <%= image_tag "search.png", alt: "Search Icon", class: "searchImg" %>
    </div>
  </div>
  <div class="categoriesSubHeader">
    <div>
      <p class="left"> Most ancient</p>
    </div>
    <div>
      <p> Most recent</p>
    </div>
    <div class="dummy">Not to show</div>
  </div>
  <%= button_to '< Sign out', destroy_user_session_path, method: :delete, class: "groupContainerButton", style: "background: #e73f3f; margin: 5px 0px 0px 90%; border-radius: 5px; border-top: 1.5px solid #898989; border-left: 1.5px solid #898989; border-right: 1px solid #858585; border-bottom: 1px solid #858585; color: aliceblue; font-family: proxima-nova, sans-serif;" %>
  <ul class="groups">
    <% @groups.each do |group| %>
      <% if user_signed_in? && group.user_id == current_user.id %>
        <li class="groupContainer">
          <div class="groupIcon">
            <%= image_tag group.icon, alt: "Group Icon", class: "groupImg" %>
          </div>
          <div class="groupNameContainer">
            <h3>
              <%= link_to group.name, group_path(group), { class: "groupName" } %>
            </h3>
            <p class="groupUpDated">
              <%= group.updated_at.strftime("%d %b %Y") %>
            </p>
          </div>
          <p class="groupAmount">$ <%= group.entities.sum(:amount) %></p>
        </li>
      <% end %>
    <% end %>
  </ul>
  <div class="newCategoryDevice">
    <%= link_to "ADD CATEGORY", new_group_path, { class: "newCategory" } %>
  </div>
</section>

app/views/groups/new.html.erb
<%= form_with model: @group, url: groups_path, method: :post, local: true, html: { class: "newCategoryForm" } do |f| %>
    <div class="newCategHeader">
      <div class ="backArrow">
        <%= link_to groups_path do %>
          <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "backArrowImg" %>
        <% end %>
      </div>
      <h2>ADD CATEGORY</h2>
      <%= f.submit "Create", class: "submitNewCategory" %>
    </div>
    <div class="fieldNameNewCategory">
      <%= f.text_field :name, autocomplete: "Group name", placeholder: "Name", class: "loginField" %>
    </div>
  
    <div class="iconGrid">
      <h2>SELECT AN ICON</h2>
      <div class="iconRow">
        <div class="iconItem">
          <%= f.radio_button :icon, "clothes.png" %>
          <%= label_tag :clothes do %>
            <%= image_tag "clothes.png", alt: "Clothes budget Icon", class: "iconImg" %>
          <% end %>
        </div>
        <div class="iconItem">
          <%= f.radio_button :icon, "entertainment.png" %>
          <%= label_tag :entertainment do %>
            <%= image_tag "entertainment.png", alt: "Entertainment budget Icon", class: "iconImg" %>
          <% end %>
        </div>
        <div class="iconItem">
          <%= f.radio_button :icon, "budget.png" %>
          <%= label_tag :feeding do %>
            <%= image_tag "budget.png", alt: "Feeding budget Icon", class: "iconImg" %>
          <% end %>
        </div>
      </div>
      <div class="iconRow">
        <div class="iconItem">
          <%= f.radio_button :icon, "house.png" %>
          <%= label_tag :house do %>
            <%= image_tag "house.png", alt: "House budget Icon", class: "iconImg" %>
          <% end %>
        </div>
        <div class="iconItem">
          <%= f.radio_button :icon, "education.png" %>
          <%= label_tag :education do %>
            <%= image_tag "education.png", alt: "Education budget Icon", class: "iconImg" %>
          <% end %>
        </div>
        <div class="iconItem">
          <%= f.radio_button :icon, "car.png" %>
          <%= label_tag :transportation do %>
            <%= image_tag "car.png", alt: "Transportation budget Icon", class: "iconImg" %>
          <% end %>
        </div>
      </div>
      <div class="iconRow">
        <div class="iconItem">
          <%= f.radio_button :icon, "pig.png" %>
          <%= label_tag :default do %>
            <%= image_tag "pig.png", alt: "Default budget Icon", class: "iconImg" %>
          <% end %>
        </div>
        <div class="iconItem">
          <%= f.radio_button :icon, "puppie.png" %>
          <%= label_tag :default do %>
            <%= image_tag "puppie.png", alt: "Default budget Icon", class: "iconImg" %>
          <% end %>
        </div>
        <div class="iconItem">
          <%= f.radio_button :icon, "hospital.png" %>
          <%= label_tag :default do %>
            <%= image_tag "hospital.png", alt: "Default budget Icon", class: "iconImg" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

app/views/groups/show.html.erb
<section class="categoryConte">
  <div class="categoryHeader">
    <div class ="backArrow">
      <%= link_to groups_path do %>
        <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "backArrowImg" %>
      <% end %>
    </div>
    <h2>TRANSACTIONS</h2>
    <div class="dummy" >Not</div>
  </div>
  <div class="category-details-container">
    <div class="categoryInfo">
      <div class="groupIcon">
        <%= image_tag @group.icon, alt: "Group Icon", class: "groupImg"%>
      </div>
      <div class="groupNameContainer">
        <h3 class="groupName">
          <%= @group.name %>
        </h3>
      </div>
    </div>
    <div class="total-amount-container">
      <p>Total:</p>
      <p>$ <%= @group.entities.sum(:amount) %></p>
    </div>
    <div class="entitiesContainer1">
      <% @entities.each do |entity| %>
        <div class="entityContainerf">
          <p><%= entity.name %></p>
          <p>$ <%= entity.amount %></p>
        </div>
        <div>
        <%= button_to "Delete", group_entity_path(@group, entity), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "deleteButton", style: "background: #e73f3f; margin: 5px 0px 0px 0%; border-radius: 5px; border-top: 1.5px solid #898989; border-left: 1.5px solid #898989; border-right: 1px solid #858585; border-bottom: 1px solid #858585; color: aliceblue; font-family: proxima-nova, sans-serif;"%>
        </div>
      <% end %>
    </div>
    <div class="newEntityDevice">
      <%= link_to "ADD AN EXPENSE", new_group_entity_path(@group), class: "newEntity" %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splashs/index.html.erb
<div class="splash">
  <div class="splash-title">
    <%= image_tag "spend-logo.png", class: "splash_logo" %>
    <h1 class="splash-text">BUDGET</h1>
  </div>
  <div class="splash-buttons-container">
    <%= button_to "LOG IN", new_user_session_path, class: "splash-button" %>
    <%= button_to "SIGN UP", new_user_registration_path,  method: :get, class: "splash-button" %>
  </div>
</div>